os:
  - Visual Studio 2017

environment:
  matrix:
    - ACTION: vs2015
    - ACTION: vs2017

platform:
  - Win32
    
configuration:
  - Release

install:
  - cmd: git submodule update
  - cmd: git clone https://github.com/ioquake/ioq3.git ../ioq3
  - premake5.exe --disable-game-qvm %ACTION%
  
build:
  project: build\$(ACTION)\ioquake3.sln
